### ISSUE TITLE
Connect backend with frontend

### ISSUE THREAD

**Issue by Ryuuji14** [gustavoerivero/Gentleman_Frontend#5]

**Comment by gustavoerivero** [comment]
@nohearth established the first connection by configuring the necessary files. The rest of the back-front communication remains to be done.

**Comment by gustavoerivero** [comment]
The login system works, i.e. if the user enters the correct data, the user is redirected to the corresponding feed.

**Comment by gustavoerivero** [comment]
Login, registration form functional with backend, however, the rest of the connections have not been implemented.
